name: Dependency audit

on:
  push:
  pull_request:

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pip-audit
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
      - name: Run pip-audit
        run: |
          python -m pip_audit -r requirements.txt || true
